### ISSUE TITLE
T2V-Turbo-v2 在VBench总分目前排名第一，是否可以加入一起对比一下

### ISSUE THREAD

**Issue by gobigrassland** [AILab-CVC/VideoGen-Eval#3]

**Comment by yyvhang** [comment]
We release the VGenEval package to obtain our prompts. If you want to see the results of the model as soon as possible, we encourage you to use it, obtaining prompts and test the model. We are still waiting for several commercial models to be open for testing, and updates will be made at that time.

**Comment by gobigrassland** [comment]
OK，Thanks!
