### ISSUE TITLE
当前测评中CogVideoX模型是否使用SAT prompt-optimized？

### ISSUE THREAD

**Issue by gobigrassland** [AILab-CVC/VideoGen-Eval#4]
是否与VBench测评中，关于CogVideoX使用一样的模型参数，且对prompt进行优化后再进行的？ https://huggingface.co/spaces/Vchitect/VBench_Leaderboard

**Comment by yyvhang** [comment]
Prompts have not been refined to maintain consistency in all model testing, including commercial models.
