### ISSUE TITLE
Missing mochi demos in google drive

### ISSUE THREAD

**Issue by xyupeng** [AILab-CVC/VideoGen-Eval#5]
Dear authors,

Many thanks to your work on such a comprehensive VideoGen evaluation project. It's great to see so many video samples from a wide range of models which are really easy to compare with. I found that the videos from mochi, the recently released open-source model, existing on the project page, but missing in google drive. Would you please do us a favor and upload them on google drive?

Thanks,
Xiangyu

**Comment by yyvhang** [comment]
Hi, the results of Mochi1 have been uploaded to Google Drive

**Comment by xyupeng** [comment]
Thanks!
